//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub mod prelude;

pub mod department;
pub mod department_role_ref;
pub mod group;
pub mod group_role_ref;
pub mod organization;
pub mod organization_role_ref;
pub mod permission;
pub mod position;
pub mod position_role_ref;
pub mod role;
pub mod system_config;
pub mod user_group_ref;
pub mod user_info;
pub mod user_role_ref;
pub mod user_wechat_info;
pub mod user;
