//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "permission")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub uuid: String,
    pub parent_uuid: Option<String>,
    pub code: Option<String>,
    pub name: String,
    pub description: Option<String>,
    pub application: Option<String>,
    pub sort: Option<i32>,
    pub node_type: Option<String>,
    pub link_url: Option<String>,
    pub ico_url: Option<String>,
    pub level: Option<i32>,
    pub path: Option<String>,
    pub org_code: Option<String>,
    pub extra: Option<Json>,
    pub remark: Option<String>,
    #[sea_orm(default_value = 0, nullable)]
    pub is_del: Option<i8>,
    pub create_time: Option<DateTime>,
    pub update_time: Option<DateTime>,
    #[sea_orm(default_value = 0, nullable)]
    pub create_by: Option<i64>,
    #[sea_orm(default_value = 0, nullable)]
    pub update_by: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
