//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub use super::department::Entity as Department;
pub use super::department_role_ref::Entity as DepartmentRoleRef;
pub use super::group::Entity as Group;
pub use super::group_role_ref::Entity as GroupRoleRef;
pub use super::organization::Entity as Organization;
pub use super::organization_role_ref::Entity as OrganizationRoleRef;
pub use super::permission::Entity as Permission;
pub use super::position::Entity as Position;
pub use super::position_role_ref::Entity as PositionRoleRef;
pub use super::role::Entity as Role;
pub use super::system_config::Entity as SystemConfig;
pub use super::user_group_ref::Entity as UserGroupRef;
pub use super::user_info::Entity as UserInfo;
pub use super::user_role_ref::Entity as UserRoleRef;
pub use super::user_wechat_info::Entity as UserWechatInfo;
pub use super::user::Entity as User;